name: fluttercontactpicker
description: Use Androids' and iOS' native contact pickers to chose phone numbers and email addresses from contacts of the users address book
version: 4.1.0
git: https://github.com/DRSchlaubi/contact_pickercop
homepage: https://github.com/DRSchlaubi/contact_picker

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  contact_picker_platform_interface: ^4.0.2
  contact_picker_web: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.schlaubi.fluttercontactpicker
        pluginClass: FlutterContactPickerPlugin
      ios:
        pluginClass: FlutterContactPickerPlugin
      web:
        default_package: contact_picker_web
