name: contact_picker_platform_interface
description: A common platform interface for the contact_picker plugin.
homepage: https://github.com/DRSchlaubi/contact_picker/tree/master/contact_picker_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.5.1

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
