name: contact_picker_web
version: 4.3.0
description: Use Chromes contact picker to chose phone numbers and email addresses from contacts of the users address book
homepage: https://github.com/DRSchlaubi/contact_picker/tree/feature/web/contact_picker_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterContactPickerPlugin
        fileName: contact_picker_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  contact_picker_platform_interface: ^4.3.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"